language: R
cache: packages
sudo: false
warnings_are_errors: true

before_install:
  - echo "$OSTYPE"
  - if [[ "$OSTYPE" != "linux-gnu" ]]; then sudo tlmgr install tlmgr install standalone xcolor booktabs multirow array psnfss amsmath rotating listings graphicx setspace caption; fi

r_packages:
  - details

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - libfftw3-dev
      - cargo

notifications:
  slack: slackr-tester:fVbBXh9OA3Lt11M6qKO8kbiP
